"""Mil-Int surface configuration — ``MilIntSettings`` Pydantic v2 model.

Mirrors :mod:`hydra.eas.settings` — a standalone settings module that the
root :class:`HydraSettings` imports (not the other way around) to avoid
circular imports.
"""

from __future__ import annotations

from pathlib import Path
from typing import Literal

from pydantic import BaseModel, Field, field_validator


_DEFAULT_TIER_IDS: tuple[int, ...] = (100, 101, 102, 103, 104, 105, 106, 107)


class MilIntSettings(BaseModel):
    """Root settings for the mil_int_public_information surface.

    Nested under :attr:`HydraSettings.mil_int`; defaults are tuned so the
    surface boots safely without any operator overrides — the
    classification gate is on, blob downloads are off, and the source
    manifest path points at the in-tree spec doc.
    """

    # --- ingestion gating -------------------------------------------------

    source_tiers: list[int] = Field(default_factory=lambda: list(_DEFAULT_TIER_IDS))
    """Tier IDs in stream_registry.yaml that belong to this surface."""

    download_blobs: bool = False
    """When True, the doc_repo adapter pulls each discovered document into
    MinIO via the ``_binary_artifact`` channel. Off by default — operators
    must opt in once a MinIO bucket is provisioned for the relevant tier."""

    blob_byte_limit: int = Field(default=25 * 1024 * 1024, ge=1024)
    """Per-document byte ceiling for blob downloads (default 25 MiB)."""

    max_docs_per_run_default: int = Field(default=25, ge=1, le=10_000)
    """Fallback ``max_docs_per_run`` when a stream config doesn't set one."""

    # --- classification gate ---------------------------------------------

    enforce_classification_gate: bool = True
    """Reject any record whose detected classification isn't UNCLASSIFIED.
    Spec §"OPERATIONAL CONSTRAINTS" item 1 is a hard requirement; this
    toggle exists only for tests that want to feed synthetic classified
    payloads through the gate."""

    classification_log_only: bool = False
    """Mutually exclusive with ``enforce_classification_gate``: when True,
    violations are logged + counted but the record is allowed through.
    Used for shadow-mode rollouts, never in production."""

    # --- standards cross-reference ---------------------------------------

    xref_seed_path: Path = Path("config/mil_int_xref.yaml")
    """Curated YAML mapping of standards across families (MIL-STD ↔ NIST SP
    ↔ STANAG ↔ DEF STAN ↔ FIPS)."""

    xref_max_results: int = Field(default=50, ge=1, le=500)

    # --- manifest --------------------------------------------------------

    manifest_path: Path = Path("specs/mil-int-surface/source_manifest.md")
    """Static doc enumerating every registered source with its access
    policy. Surfaced by the manifest router; regenerated by the manifest
    generator when registry contents change."""

    # --- search / faceting ----------------------------------------------

    search_default_page_size: int = Field(default=20, ge=1, le=200)
    search_max_page_size: int = Field(default=100, ge=1, le=500)
    search_index_name: str = "hydra-mil-int-records"

    # --- doctrine feed ---------------------------------------------------

    doctrine_feed_lookback_days: int = Field(default=180, ge=1, le=3650)
    doctrine_feed_max_items: int = Field(default=100, ge=1, le=1000)

    # --- compliance overlay ---------------------------------------------

    compliance_families: list[Literal["STIG", "NIST_SP_800", "NSA_CSI"]] = Field(
        default_factory=lambda: ["STIG", "NIST_SP_800", "NSA_CSI"]
    )

    @field_validator("source_tiers")
    @classmethod
    def _validate_tiers(cls, v: list[int]) -> list[int]:
        for tid in v:
            if tid < 100 or tid > 199:
                raise ValueError(
                    f"Mil-Int source_tiers must be in 100-199; got {tid}"
                )
        if len(v) != len(set(v)):
            raise ValueError("source_tiers contains duplicates")
        return v


__all__ = ["MilIntSettings"]
